export const REQUESTING_MODEL_DATA = 'REQUESTING_MODEL_DATA'
export const RECEIVING_MODEL_DATA = 'RECEIVING_MODEL_DATA'
export const STARTING_MODEL_REQUESTS = 'STARTING_MODEL_REQUESTS'
export const ENDING_MODEL_REQUESTS = 'ENDING_MODEL_REQUESTS'